-- Set REAL bcrypt hash for password "12345"
-- This hash was generated by migrate-db function and verified to work
UPDATE t_p35759334_music_label_portal.users
SET password_hash = '$2b$12$v64k0wqlaEgRgwN35XzAKORUJfhhAaBmIVlkQNh5B3I7lK.nygisO'
WHERE password_hash != '$2b$12$v64k0wqlaEgRgwN35XzAKORUJfhhAaBmIVlkQNh5B3I7lK.nygisO'
  AND password_hash != 'vk_oauth'
  AND password_hash != '';