import funcUrls from '../../backend/func2url.json';

export const API_ENDPOINTS = {
  TICKET_COMMENTS: funcUrls['ticket-comments'],
  CHANGE_PASSWORD: funcUrls['change-password'],
  GEN_HASH: funcUrls['gen-hash'],
  MIGRATE_DB: funcUrls['migrate-db'],
  VK_POSTS: funcUrls['vk-posts'],
  TELEGRAM_AUTH: funcUrls['telegram-auth'],
  PITCHING: funcUrls['pitching'],
  CREATE_NOTIFICATION: funcUrls['create-notification'],
  RELEASE_ANALYTICS: funcUrls['release-analytics'],
  NOTIFICATIONS: funcUrls['notifications'],
  RELEASES: funcUrls['releases'],
  UNREAD_COUNTS: funcUrls['unread-counts'],
  WEEKLY_REPORT: funcUrls['weekly-report'],
  TASKS: funcUrls['tasks'],
  MESSAGES: funcUrls['messages'],
  TICKET_ANALYTICS: funcUrls['ticket-analytics'],
  TASK_COMMENTS: funcUrls['task-comments'],
  UPLOAD_FILE: funcUrls['upload-file'],
  SUBMISSIONS: funcUrls['submissions'],
  UPLOAD_REPORTS: funcUrls['upload-reports'],
  DEADLINE_REMINDER: funcUrls['deadline-reminder'],
  TELEGRAM_BOT: funcUrls['telegram-bot'],
  USERS: funcUrls['users'],
  TICKETS: funcUrls['tickets'],
  AUTH: funcUrls['auth'],
} as const;
